import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata: Metadata = {
  title: "CodeEmpowement",
  description: "Generated by CodeEmpowement",
  icons: [{ rel: "icon", url: "/jira.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex flex-col">
        <div>
          <Navbar/>
        </div>
        <main>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </main>
        <Footer/>
        </body>
    </html>
  );
}
